---
micronaut:
  application:
    name: demo

---
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/demo
#    driverClassName: org.postgresql.Driver
#    username: demo
#    password: '12345678'
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES

logging:
  level:
    root: INFO
    cn.hillwind.wx: DEBUG
    com.github.binarywang: DEBUG
    io.micronaut.data.query: DEBUG