---
micronaut:
  application:
    name: demo

---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/pulsesurveydb`}
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    dialect: POSTGRES

logging:
  level:
    root: INFO
    cn.hillwind.wx: DEBUG
    com.github.binarywang: DEBUG
    io.micronaut.data.query: DEBUG